import { Box } from '@mui/system'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Wrapper, Status } from '@googlemaps/react-wrapper'
import { CircularProgress, Stack, Typography } from '@mui/material'
import ErrorIcon from '@mui/icons-material/Error'
import { useRef, useEffect } from 'react'

export default function Home() {
  const render = (status: Status) => {
    switch (status) {
      case Status.LOADING:
        return <CircularProgress />
      case Status.FAILURE:
        return (
          <Stack direction="column" spacing={4}>
            <ErrorIcon />
            <Typography color="text.secondary">エラーが発生しました</Typography>
          </Stack>
        )
      case Status.SUCCESS:
        return <MyMapComponent center={{ lat: 35.654291, lng: 139.750533 }} zoom={15} />
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box sx={{ width: '100%', height: '100vh' }}>
        <Wrapper apiKey="AIzaSyAQtZaDCQybQWgd-uOQD-jN7vJnontAXtY" render={render} />
      </Box>
    </>
  )
}

function MyMapComponent({ center, zoom }: { center: google.maps.LatLngLiteral; zoom: number }) {
  const ref = useRef<HTMLDivElement>(null)
  const initRef = useRef(false)

  useEffect(() => {
    if (!ref.current) return
    if (initRef.current) return

    new google.maps.Map(ref.current, {
      center: { lat: center.lat, lng: center.lng },
      zoom,
    })
    initRef.current = true
  }, [center.lat, center.lng, zoom])

  return <Box ref={ref} id="map" sx={{ width: '100%', height: '100%' }} />
}
