import { Status, Wrapper } from '@googlemaps/react-wrapper'
import ErrorIcon from '@mui/icons-material/Error'
import { AppBar, Button, CircularProgress, Divider, Paper, Stack, Toolbar, Typography, useTheme } from '@mui/material'
import { Box } from '@mui/system'
import { GetStaticProps } from 'next'
import Head from 'next/head'
import { useEffect, useRef } from 'react'
import { AdmissionDifficulty, getAdmissionDifficulty } from '../lib/model/nursery-school'
import { getAllNurserySchoolListSets, LocalNurserySchoolListSet } from '../lib/model/nursery-school-list'
import { blue } from '../styles/theme'

interface Props {
  nurserySets: LocalNurserySchoolListSet[]
}

export default function Home({ nurserySets }: Props) {
  const render = (status: Status) => {
    switch (status) {
      case Status.LOADING:
        return <CircularProgress />
      case Status.FAILURE:
        return (
          <Stack direction="column" spacing={4}>
            <ErrorIcon />
            <Typography color="text.secondary">エラーが発生しました</Typography>
          </Stack>
        )
      case Status.SUCCESS:
        return <MyMapComponent center={{ lat: 35.654291, lng: 139.750533 }} zoom={15} nurserySets={nurserySets} />
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppBar color="transparent" elevation={0}>
        <Toolbar>
          <Filters />
        </Toolbar>
      </AppBar>

      <Box sx={{ width: '100%', height: '100vh' }}>
        <Wrapper apiKey="AIzaSyAQtZaDCQybQWgd-uOQD-jN7vJnontAXtY" render={render} />
      </Box>
    </>
  )
}

function Filters() {
  const theme = useTheme()

  return (
    <Paper elevation={1} sx={{ borderRadius: 1000, paddingX: 1 }}>
      <Stack
        direction="row"
        spacing={1}
        divider={
          <Divider
            orientation="vertical"
            flexItem
            style={{ marginTop: theme.spacing(1), marginBottom: theme.spacing(1) }}
          />
        }
      >
        <Button color="primary">2022年4月入園</Button>
        <Button color="primary">子どもの年齢指定なし</Button>
      </Stack>
    </Paper>
  )
}

function MyMapComponent({
  center,
  zoom,
  nurserySets,
}: {
  center: google.maps.LatLngLiteral
  zoom: number
  nurserySets: LocalNurserySchoolListSet[]
}) {
  const ref = useRef<HTMLDivElement>(null)
  const mapRef = useRef<google.maps.Map>()
  const markersRef = useRef<google.maps.Marker[]>([])

  useEffect(() => {
    if (!ref.current) return
    if (mapRef.current) return

    mapRef.current = new google.maps.Map(ref.current, {
      center: { lat: center.lat, lng: center.lng },
      zoom,
    })
  }, [center.lat, center.lng, zoom])

  useEffect(() => {
    markersRef.current = createMarkers(mapRef.current!, nurserySets)

    return () => {
      markersRef.current.forEach(m => m.setMap(null))
    }
  }, [nurserySets])

  return <Box ref={ref} id="map" sx={{ width: '100%', height: '100%' }} />
}

const markerPath =
  'M20.8737 31.495C27.2804 29.7873 32 23.9448 32 17C32 8.71573 25.2843 2 17 2C8.71573 2 2 8.71573 2 17C2 23.9448 6.71957 29.7873 13.1263 31.495L17 41L20.8737 31.495Z'

function createMarkers(map: google.maps.Map, nurserySets: LocalNurserySchoolListSet[]) {
  const markers: google.maps.Marker[] = []
  for (const nurserySet of nurserySets) {
    for (const nursery of nurserySet.nurseryShoolList) {
      const markerStyle = difficultyToStyle[getAdmissionDifficulty(nursery, nurserySet, null)]
      const marker = new google.maps.Marker({
        map,
        title: nursery.name,
        position: { lat: nursery.location.latitude, lng: nursery.location.longitude },
        icon: {
          fillColor: markerStyle.color,
          fillOpacity: 1,
          strokeColor: blue[90],
          strokeWeight: 1.5,
          path: markerPath,
        },
      })
      markers.push(marker)
    }
  }
  return markers
}

const difficultyToStyle = Object.freeze<Record<AdmissionDifficulty, { color: string; label: string }>>({
  [AdmissionDifficulty.Easy]: { color: blue[50], label: '入りやすい' },
  [AdmissionDifficulty.Moderate]: { color: blue[20], label: 'やや入りやすい' },
  [AdmissionDifficulty.Hard]: { color: blue[10], label: '入りにくい' },
})

export const getStaticProps: GetStaticProps<Props> = () => {
  return {
    props: {
      nurserySets: getAllNurserySchoolListSets(),
    },
  }
}
