import { Status, Wrapper } from '@googlemaps/react-wrapper'
import ErrorIcon from '@mui/icons-material/Error'
import { CircularProgress, Stack, Typography } from '@mui/material'
import { Box } from '@mui/system'
import { GetStaticProps } from 'next'
import Head from 'next/head'
import { useEffect, useRef } from 'react'
import { getAllNurserySchoolListSets, LocalNurserySchoolListSet } from '../lib/model/nursery-school-list'

interface Props {
  nurserySets: LocalNurserySchoolListSet[]
}

export default function Home({ nurserySets }: Props) {
  const render = (status: Status) => {
    switch (status) {
      case Status.LOADING:
        return <CircularProgress />
      case Status.FAILURE:
        return (
          <Stack direction="column" spacing={4}>
            <ErrorIcon />
            <Typography color="text.secondary">エラーが発生しました</Typography>
          </Stack>
        )
      case Status.SUCCESS:
        return <MyMapComponent center={{ lat: 35.654291, lng: 139.750533 }} zoom={15} nurserySets={nurserySets} />
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box sx={{ width: '100%', height: '100vh' }}>
        <Wrapper apiKey="AIzaSyAQtZaDCQybQWgd-uOQD-jN7vJnontAXtY" render={render} />
      </Box>
    </>
  )
}

function MyMapComponent({
  center,
  zoom,
  nurserySets,
}: {
  center: google.maps.LatLngLiteral
  zoom: number
  nurserySets: LocalNurserySchoolListSet[]
}) {
  const ref = useRef<HTMLDivElement>(null)
  const mapRef = useRef<google.maps.Map>()
  const markersRef = useRef<google.maps.Marker[]>([])

  useEffect(() => {
    if (!ref.current) return
    if (mapRef.current) return

    mapRef.current = new google.maps.Map(ref.current, {
      center: { lat: center.lat, lng: center.lng },
      zoom,
    })
  }, [center.lat, center.lng, zoom])

  useEffect(() => {
    markersRef.current = createMarkers(mapRef.current!, nurserySets)
  }, [nurserySets])

  return <Box ref={ref} id="map" sx={{ width: '100%', height: '100%' }} />
}

function createMarkers(map: google.maps.Map, nurserySets: LocalNurserySchoolListSet[]) {
  const markers: google.maps.Marker[] = []
  for (const nurserySet of nurserySets) {
    for (const nursery of nurserySet.nurseryShoolList) {
      const marker = new google.maps.Marker({
        map,
        title: nursery.name,
        position: { lat: nursery.location.latitude, lng: nursery.location.longitude },
      })
      markers.push(marker)
    }
  }
  return markers
}

export const getStaticProps: GetStaticProps<Props> = () => {
  return {
    props: {
      nurserySets: getAllNurserySchoolListSets(),
    },
  }
}
